"""A small starter bestiary drawn from SRD 5.2 (Creative Commons, CC-BY-4.0).
Curated subset with original wording — enough to populate a fresh campaign;
extend via import or the compendium. Full stat blocks: ability scores, traits,
actions, senses. Re-seeding enriches existing entries that predate the full
blocks (matched by name) without touching your custom numbers."""

STARTER_BESTIARY = [
    {"name": "Goblin", "size": "Small", "creatureType": "Humanoid", "alignment": "Neutral Evil",
     "ac": 15, "hp": 7, "cr": "1/4", "xp": 50, "speed": "30 ft",
     "abilityScores": {"str": 8, "dex": 14, "con": 10, "int": 10, "wis": 8, "cha": 8},
     "skills": ["Stealth +6"], "senses": "Darkvision 60 ft, passive Perception 9",
     "languages": "Common, Goblin",
     "traits": "Nimble Escape. Can take the Disengage or Hide action as a bonus action on each of its turns.",
     "actions": "Scimitar. Melee: +4 to hit, 1d6+2 slashing.\nShortbow. Ranged 80/320 ft: +4 to hit, 1d6+2 piercing.",
     "notes": ""},
    {"name": "Orc", "size": "Medium", "creatureType": "Humanoid", "alignment": "Chaotic Evil",
     "ac": 13, "hp": 15, "cr": "1/2", "xp": 100, "speed": "30 ft",
     "abilityScores": {"str": 16, "dex": 12, "con": 16, "int": 7, "wis": 11, "cha": 10},
     "skills": ["Intimidation +2"], "senses": "Darkvision 60 ft, passive Perception 10",
     "languages": "Common, Orc",
     "traits": "Aggressive. As a bonus action, can move up to its speed toward a hostile creature it can see.",
     "actions": "Greataxe. Melee: +5 to hit, 1d12+3 slashing.\nJavelin. Melee or ranged 30/120 ft: +5 to hit, 1d6+3 piercing.",
     "notes": ""},
    {"name": "Skeleton", "size": "Medium", "creatureType": "Undead", "alignment": "Lawful Evil",
     "ac": 13, "hp": 13, "cr": "1/4", "xp": 50, "speed": "30 ft",
     "abilityScores": {"str": 10, "dex": 14, "con": 15, "int": 6, "wis": 8, "cha": 5},
     "senses": "Darkvision 60 ft, passive Perception 9",
     "languages": "Understands the languages it knew in life but can't speak",
     "traits": "Vulnerable to bludgeoning damage. Immune to poison damage; can't be poisoned or gain exhaustion.",
     "actions": "Shortsword. Melee: +4 to hit, 1d6+2 piercing.\nShortbow. Ranged 80/320 ft: +4 to hit, 1d6+2 piercing.",
     "notes": ""},
    {"name": "Zombie", "size": "Medium", "creatureType": "Undead", "alignment": "Neutral Evil",
     "ac": 8, "hp": 22, "cr": "1/4", "xp": 50, "speed": "20 ft",
     "abilityScores": {"str": 13, "dex": 6, "con": 16, "int": 3, "wis": 6, "cha": 5},
     "senses": "Darkvision 60 ft, passive Perception 8",
     "languages": "Understands the languages it knew in life but can't speak",
     "traits": "Undead Fortitude. When reduced to 0 HP by damage that isn't radiant or a critical hit, it makes a CON save (DC 5 + damage taken); on a success it drops to 1 HP instead.",
     "actions": "Slam. Melee: +3 to hit, 1d6+1 bludgeoning.",
     "notes": ""},
    {"name": "Wolf", "size": "Medium", "creatureType": "Beast", "alignment": "Unaligned",
     "ac": 13, "hp": 11, "cr": "1/4", "xp": 50, "speed": "40 ft",
     "abilityScores": {"str": 12, "dex": 15, "con": 12, "int": 3, "wis": 12, "cha": 6},
     "skills": ["Perception +3", "Stealth +4"], "senses": "Passive Perception 13",
     "languages": "—",
     "traits": "Keen Hearing and Smell. Advantage on Perception checks that rely on hearing or smell.\nPack Tactics. Advantage on attack rolls against a creature if an ally is within 5 ft of it.",
     "actions": "Bite. Melee: +4 to hit, 2d4+2 piercing; target makes a DC 11 STR save or is knocked prone.",
     "notes": ""},
    {"name": "Dire Wolf", "size": "Large", "creatureType": "Beast", "alignment": "Unaligned",
     "ac": 14, "hp": 37, "cr": "1", "xp": 200, "speed": "50 ft",
     "abilityScores": {"str": 17, "dex": 15, "con": 15, "int": 3, "wis": 12, "cha": 7},
     "skills": ["Perception +3", "Stealth +4"], "senses": "Passive Perception 13",
     "languages": "—",
     "traits": "Keen Hearing and Smell. Advantage on Perception checks that rely on hearing or smell.\nPack Tactics. Advantage on attack rolls against a creature if an ally is within 5 ft of it.",
     "actions": "Bite. Melee: +5 to hit, 2d6+3 piercing; target makes a DC 13 STR save or is knocked prone.",
     "notes": ""},
    {"name": "Bandit", "size": "Medium", "creatureType": "Humanoid", "alignment": "Any Non-Lawful",
     "ac": 12, "hp": 11, "cr": "1/8", "xp": 25, "speed": "30 ft",
     "abilityScores": {"str": 11, "dex": 12, "con": 12, "int": 10, "wis": 10, "cha": 10},
     "senses": "Passive Perception 10", "languages": "Any one language (usually Common)",
     "traits": "",
     "actions": "Scimitar. Melee: +3 to hit, 1d6+1 slashing.\nLight Crossbow. Ranged 80/320 ft: +3 to hit, 1d8+1 piercing.",
     "notes": ""},
    {"name": "Bandit Captain", "size": "Medium", "creatureType": "Humanoid", "alignment": "Any Non-Lawful",
     "ac": 15, "hp": 65, "cr": "2", "xp": 450, "speed": "30 ft",
     "abilityScores": {"str": 15, "dex": 16, "con": 14, "int": 14, "wis": 11, "cha": 14},
     "saves": ["STR +4", "DEX +5", "WIS +2"], "skills": ["Athletics +4", "Deception +4"],
     "senses": "Passive Perception 10", "languages": "Any two languages",
     "traits": "",
     "actions": "Multiattack. Two scimitar attacks and one dagger attack.\nScimitar. Melee: +5 to hit, 1d6+3 slashing.\nDagger. Melee or ranged 20/60 ft: +5 to hit, 1d4+3 piercing.\nParry (Reaction). Adds 2 to its AC against one melee attack that would hit it (must see the attacker and be wielding a melee weapon).",
     "notes": ""},
    {"name": "Guard", "size": "Medium", "creatureType": "Humanoid", "alignment": "Any",
     "ac": 16, "hp": 11, "cr": "1/8", "xp": 25, "speed": "30 ft",
     "abilityScores": {"str": 13, "dex": 12, "con": 12, "int": 10, "wis": 11, "cha": 10},
     "skills": ["Perception +2"], "senses": "Passive Perception 12",
     "languages": "Any one language (usually Common)",
     "traits": "",
     "actions": "Spear. Melee or ranged 20/60 ft: +3 to hit, 1d6+1 piercing (1d8+1 if used two-handed in melee).",
     "notes": ""},
    {"name": "Giant Spider", "size": "Large", "creatureType": "Beast", "alignment": "Unaligned",
     "ac": 14, "hp": 26, "cr": "1", "xp": 200, "speed": "30 ft, climb 30 ft",
     "abilityScores": {"str": 14, "dex": 16, "con": 12, "int": 2, "wis": 11, "cha": 4},
     "skills": ["Stealth +7"], "senses": "Blindsight 10 ft, darkvision 60 ft, passive Perception 10",
     "languages": "—",
     "traits": "Spider Climb. Can climb difficult surfaces, including ceilings, without a check.\nWeb Sense. While touching a web, knows the location of other creatures touching the same web.\nWeb Walker. Ignores movement restrictions caused by webbing.",
     "actions": "Bite. Melee: +5 to hit, 1d8+3 piercing plus 2d8 poison (DC 11 CON save for half; if the poison drops the target to 0 HP, it is stable but poisoned and paralyzed for 1 hour).\nWeb (Recharge 5–6). Ranged 30/60 ft: +5 to hit; target is restrained by webbing (DC 12 STR to break free; the web is AC 10, 5 HP, vulnerable to fire).",
     "notes": ""},
    {"name": "Ogre", "size": "Large", "creatureType": "Giant", "alignment": "Chaotic Evil",
     "ac": 11, "hp": 59, "cr": "2", "xp": 450, "speed": "40 ft",
     "abilityScores": {"str": 19, "dex": 8, "con": 16, "int": 5, "wis": 7, "cha": 7},
     "senses": "Darkvision 60 ft, passive Perception 8", "languages": "Common, Giant",
     "traits": "",
     "actions": "Greatclub. Melee: +6 to hit, 2d8+4 bludgeoning.\nJavelin. Melee or ranged 30/120 ft: +6 to hit, 2d6+4 piercing.",
     "notes": ""},
    {"name": "Brown Bear", "size": "Large", "creatureType": "Beast", "alignment": "Unaligned",
     "ac": 11, "hp": 34, "cr": "1", "xp": 200, "speed": "40 ft, climb 30 ft",
     "abilityScores": {"str": 19, "dex": 10, "con": 16, "int": 2, "wis": 13, "cha": 7},
     "skills": ["Perception +3"], "senses": "Passive Perception 13", "languages": "—",
     "traits": "Keen Smell. Advantage on Perception checks that rely on smell.",
     "actions": "Multiattack. One bite attack and one claws attack.\nBite. Melee: +5 to hit, 1d8+4 piercing.\nClaws. Melee: +5 to hit, 2d6+4 slashing.",
     "notes": ""},
    {"name": "Cultist", "size": "Medium", "creatureType": "Humanoid", "alignment": "Any Non-Good",
     "ac": 12, "hp": 9, "cr": "1/8", "xp": 25, "speed": "30 ft",
     "abilityScores": {"str": 11, "dex": 12, "con": 10, "int": 10, "wis": 11, "cha": 10},
     "skills": ["Deception +2", "Religion +2"], "senses": "Passive Perception 10",
     "languages": "Any one language (usually Common)",
     "traits": "Dark Devotion. Advantage on saves against being charmed or frightened.",
     "actions": "Scimitar. Melee: +3 to hit, 1d6+1 slashing.",
     "notes": ""},
    {"name": "Acolyte", "size": "Medium", "creatureType": "Humanoid", "alignment": "Any",
     "ac": 10, "hp": 9, "cr": "1/4", "xp": 50, "speed": "30 ft",
     "abilityScores": {"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 14, "cha": 11},
     "skills": ["Medicine +4", "Religion +2"], "senses": "Passive Perception 12",
     "languages": "Any one language (usually Common)",
     "traits": "Spellcasting (WIS, DC 12, +4 to hit). Prepared: sacred flame, light, thaumaturgy, bless, cure wounds, sanctuary.",
     "actions": "Club. Melee: +2 to hit, 1d4 bludgeoning.\nSacred Flame. DC 12 DEX save or 1d8 radiant.",
     "notes": ""},
    {"name": "Mage", "size": "Medium", "creatureType": "Humanoid", "alignment": "Any",
     "ac": 12, "hp": 40, "cr": "6", "xp": 2300, "speed": "30 ft",
     "abilityScores": {"str": 9, "dex": 14, "con": 11, "int": 17, "wis": 12, "cha": 11},
     "saves": ["INT +6", "WIS +4"], "skills": ["Arcana +6", "History +6"],
     "senses": "Passive Perception 11", "languages": "Any four languages",
     "traits": "Spellcasting (INT, DC 14, +6 to hit). Notable: fire bolt, mage armor, magic missile, shield, misty step, fireball, counterspell, greater invisibility, cone of cold.",
     "actions": "Fire Bolt. Ranged 120 ft: +6 to hit, 2d10 fire.\nFireball. 20-ft radius, DC 14 DEX save, 8d6 fire (half on success).",
     "notes": ""},
]
